### ISSUE TITLE
[Linux] Chrome / Chromium extension not detecting application

### ISSUE THREAD

**Issue by yochananmarqos** [setvisible/DownZemAll#11]
I installed `launcher-manifest-chrome.json` as  `/etc/chromium/native-messaging-hosts/DownRightNow.json` for Chromium  and `/etc/opt/chrome/native-messaging-hosts/DownRightNow.json` for Chrome, but neither detect the application in `/opt/downzemall/`. However, I also installed `launcher-manifest-firefox.json` as `/usr/lib/mozilla/native-messaging-hosts/DownRightNow.json` and Firefox detects it. 

```
  "path": "/opt/downzemall/launcher",
```

```
/opt/downzemall/
├── DownZemAll
├── launcher
├── locale
│   ├── dza_ar_EG.qm
│   ├── dza_de_DE.qm
│   ├── dza_en_US.qm
│   ├── dza_es_ES.qm
│   ├── dza_fr_FR.qm
│   ├── dza_ko_KR.qm
│   ├── dza_pt_PT.qm
│   ├── dza_ru_RU.qm
│   └── dza_zh_CN.qm
├── queue.json
└── youtube-dl -> /usr/bin/youtube-dl
```

**Comment by yochananmarqos** [comment]
I just updated to 2.0.4 and updated the extension manually since it's not yet available on the Chrome web store. Same deal.

**Comment by setvisible** [comment]
I just saw the AUR link. Nice work!

It's a bit cumbersome to install the app on Linux. At the moment there are still opened issues (especially to make a valid AppImage..), so it's great to see you achieved to install it (at least manually) on ArchLinux and it worked.

FYI sometimes the web-extension addon is in a lower version (for instance 2.0.3) while the app is in a more recent version (like 2.0.4). It's ok, because the addon didn't change between v2.0.3 and v2.0.4. The addon's upgrade on the Firefox/Chrome webstores isn't automatic, and generally I don't make the effort to upgrade when the change concerns the version number only. This decision pattern could be called a lazy non-upgrade.

If you need anything, let me know.

**Comment by setvisible** [comment]
Possible solution:
https://github.com/setvisible/DownZemAll/issues/17#issuecomment-731737932

**Comment by yochananmarqos** [comment]
Copying it to ~/.config/chromium/NativeMessagingHosts doesn't work. All the other extensions I have installed that place files in either place work fine. 

```
❯ ls /etc/chromium/native-messaging-hosts
DownRightNow.json  io.keybase.kbnm.json  me.f1u77y.web_media_controller.json  org.gnome.chrome_gnome_shell.json  org.gnome.shell.extensions.gsconnect.json
```

**Comment by setvisible** [comment]
Maybe rename the file to **"com.setvisible.downrightnow.json"** instead of **"DownRightNow.json"**

full path : `~/.config/chromium/NativeMessagingHosts/com.setvisible.downrightnow.json`

For Firefox, it's a different convention:
 `~/.mozilla/native-messaging-hosts/DownRightNow.json`

For info, read last section of :
https://wiki.mozilla.org/WebExtensions/Native_Messaging

Cheers

**Comment by yochananmarqos** [comment]
Aha! That fixes it. I've updated the AUR package.
