### ISSUE TITLE
Small Feature request

### ISSUE THREAD

**Issue by theromorph** [setvisible/DownZemAll#15]
Hello. And thank you for your time spent on this program.

I'd like to have an option "Close to system tray", not only "Minimize to system tray". And nice option to minimize with ESC key - ESC pressed and DZA minimized to system tray.

will look forward.

**Comment by setvisible** [comment]
Hello!
What is your OS?
I think your idea could be two independent options, in Preferences. Unchecked by default, because most people (especially on Windows) will not understand if the app doesn't close when they click on the top-right close button, or if it closes when they press Escape (on Windows, Escape closes dialog boxes but not the main application in general).

Regards

**Comment by theromorph** [comment]
Hola.
I use Windpws Server 2012 as my workstation.
Of course, I meant two different options, may be in advanced section.

**Comment by setvisible** [comment]
The option that minimizes the application on Escape key pressed should be available on v2.1.0

PS: sorry I forgot to implement the other option (minimize -not close- when close button is pressed)

**Comment by theromorph** [comment]
Hope to see it in near future :)

**Comment by theromorph** [comment]
By the way versions of the App and of the plugin are not synchronized?

**Comment by setvisible** [comment]
**A: Synchronization**

To release a new version, I create a new tag on master branch (for example: "v2.1.0"). Travis and Appveyor build the project (Qt app, launcher and the Firefox/Chrome extension), and if it passes all the tests, they posted them on Github. Then I click "Publish" on github, write a short release note, and generally it's finished.

That's why you can see the current versions are 
 - v2.1.0 for the Qt app 
 - v2.0.7 for the extension description on chrome App Store and Mozilla App Store

Indeed, the Firefox/Chrome extension is very simple (it's just a thin layer of HTML+Javascript). Generally it doesn't change between two project releases. Because I'm lazy, I don't upgrade the Mozilla App store and Chrome App Store, when the extension hasn't changed, that's why it seems to stay some versions behind. 

Maybe there's a way to automate the extension upgrade on Moz Addons Store and Chrome Web Store, but I don't know it.

**A: CRX Version**

The extension is in the release page, a *.ZIP for Chrome and a *.XPI for Firefox (which is a zip too). 

(I don't know much about CRX, but it seems to be a ZIP format too)

**Comment by theromorph** [comment]
Hola.

 

Just downloaded and installed 2.1.0 version from the site. Nevertheless, it says it 2.0.8. Even after update from the app it says the same.

 

-- 

With respect,

 

Peter Zhigulin, Head of IP/MPLS department

United Company LLC «Svyaznoy Chain»

===== ON DUTY =====

pho. +7 495 7717311 (ext. 15551)

pho. +7 495 7777710 (ext. 15551)

===== ON DUTY =====

mob. +7 916 8284772

mob. +7 964 5007552

pho. +7 495 7717311 (ext. 12997)

pho. +7 495 7777710 (ext. 12997)

fax. +7 495 9701022

e-mail: theromorph@MustDie.RU

e-mail: zpit@el-sv.ru

e-mail: zpit@svyaznoy.ru

**Comment by setvisible** [comment]
Feature is implemented so I close it.
Regards
