### ISSUE TITLE
DownZemAll crashes when adding torrent file with characters > ASCII 127

### ISSUE THREAD

**Issue by BackSpace54** [setvisible/DownZemAll#24]
Hi,
with Windows version when adding or drag & dropping .torrent files with a name containing ascii characters > 127 (one or several characters e.g. ä Ý Ø à and so on), DownZemAll crashes instantly and closes.
Could you check the issue?
Thanks.

**Comment by setvisible** [comment]
Hi,
I'm glad to announce that this issue has been successfully reproduced.

It seemed to be due to the initial save of the .torrent (before the download starts). So I fixed the naming by replacing all non-ASCII chars by simple _'s . Now arabic torrents look like "____-______._____.torrent" but they don't crash the program anymore. 

(Fix available in currently compiling v2.2.2). 

Note: If it crashes again, maybe it's caused by another part of the program: where the program starts to write the contained files of the torrent (not the torrent itself), the probability to crash is high if they have special characters. I didn't protected this part yet and will only if needed. Let's see the shape of the things to come.

Regards,
