### ISSUE TITLE
Slow video download speeds

### ISSUE THREAD

**Issue by h4aLkon** [setvisible/DownZemAll#48]
Hello. I'm getting very slow download speeds from Youtube - for example if I use a different application like Youtube Downloader HD https://www.youtubedownloaderhd.com/ the download is very fast no matter which video I try to download. Can you please check the issue?

**Comment by setvisible** [comment]
Hello,

The issue comes from the fact that the youtube-dl project is a lot behind its forks evolution at the moment. The solution is to use the most recent fork instead of the main project, as the speed seems solved in the fork...

Quick-n-dirty manual fix:
1) download the last release of yt-dlp.exe here at https://github.com/yt-dlp/yt-dlp
2) rename yt-dlp.exe to youtube-dl.exe, and place it in the DZA directory
3) restart DownZemAll.exe

I could likely fix that in the next DownZemAll version.

**Comment by h4aLkon** [comment]
Yep. Your fix works. Thank you so much!
