### ISSUE TITLE
[Feature Request] Allow the user to specify the path to DownZemAll.exe in the Firefox Addon

### ISSUE THREAD

**Issue by LOuroboros** [setvisible/DownZemAll#5]
Title. I installed DownZemAll in a certain folder of my External HDD, and if I install the addon for Firefox, it seems to expect me to have it installed in its default directory without even giving me the choice of manually choosing the path to DownZemAll.exe for the addon to read.

**Comment by setvisible** [comment]
In your install directory there should be a "install.bat" script, that writes the directory's path to the registry so that Firefox knows where is the exe.

Indeed, Firefox's WebExtension communicates with third party application (i.e. DownZemAll.exe) through the "native messaging" mechanism:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging

Basically on Windows, Firefox reads the Registry, that contains the path the *.exe. It's probably not possible to write into the registry from Firefox extensions, for obvious safety reasons :)
