### ISSUE TITLE
Use system libtorrent instead of building static libs

### ISSUE THREAD

**Issue by yochananmarqos** [setvisible/DownZemAll#50]
Can you add a Cmake flag to use the system `libtorrent` instead of building it? I tried patching out a few things, but it didn't work as it couldn't find `libtorrent/fwd.hpp`.

**Comment by setvisible** [comment]
Hi,

Could you be more specific?
The Travis CI and AppveyorCI don't show this (maybe) link error: 
https://app.travis-ci.com/github/setvisible/DownZemAll/builds/241310066

Maybe the problem is your missing cmake path settings?

Regards

**Comment by yochananmarqos** [comment]
No, it builds fine as is. I said I tried patching out building the static `libtorrent`, but couldn't figure out how to make it use the system `libtorrent` package.

**Comment by setvisible** [comment]
Hi,
Do you mean building the libtorrent apart and linking it dynamically to DZA, instead of the current static build?
It's a lot of work to reengineer all this... Libtorrent isn't easy to understand. I'm not sure I have the time to do it.
Maybe let's keep it for the future, when the current implementation will stop to work (and when going for libtorrent 2.0 would be the only solution to fix it...)?
Cheers

**Comment by yochananmarqos** [comment]
No, I mean don't build it at all and depend on `libtorrent` as a dependency.

**Comment by yochananmarqos** [comment]
> Maybe the problem is your missing cmake path settings?

I guess that was it. I figured out how to do it with 3.0.0. See my AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=downzemall).
