### ISSUE TITLE
Could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by RafaelLinux** [setvisible/DownZemAll#78]
```
 ./DownZemAll_v2.5.8_x86_64_no_launcher.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
```

I verified xcb is installed.  What more to check?

Operating System: openSUSE Tumbleweed 20220719
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.11-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by setvisible** [comment]
Hi,

After some researches and tests with Ubuntu 22.04, it appeared that some libraries where missing. Indeed typing the following command helps to find the missing libs:

> ldd ./DownZemAll
> ldd ./libQt6Core.so
> ldd ./libQt6Gui.so
> ldd ./libQt6OpenGL
>...and so on

Thus, these libraries have been added in [version 3.0.1](https://github.com/setvisible/DownZemAll/releases/tag/v3.0.1) released today.

From there, the xcb issue still appears, but it's more a config issue. I typed the next command to ensure XCB (instead of Wayland) is used, then set the `LD_LIBRARY_PATH` and executed the application more or less correctly:

> export QT_QPA_PLATFORM=xcb
> export LD_LIBRARY_PATH= '/path/to/DownZemAll'
> ./DownZemAll

It was a kind of library linking issue.

It would be nice if an expert of Linux could help to fix it definitively... Currently I just changed the command in the shortcut `DownZemAll.desktop`; There's certainly a more elegant way to solve it :)

So I'll keep this ticket opened and will close the others.

Cheers,

**Comment by RafaelLinux** [comment]
Latest AppImage version works without any issues. Theme, however, doesn't match global Plasma one (I'm using dark theme).

**Comment by eadmaster** [comment]
still not working even with these commands:

> export QT_QPA_PLATFORM=xcb
> export LD_LIBRARY_PATH= '/path/to/DownZemAll'
> ./DownZemAll
> 
> Fatal: Cannot mix incompatible Qt library (6.2.4) with this library (6.3.1)
> Aborted (core dumped)

**Comment by RafaelLinux** [comment]
As far as I know, no "Appimage" versions are being released (except for some "non-launcher" versions). I would like a much better AppImage version than the compressed and installable version, but I understand that this involves difficulties and requires more time.

At the moment, I don't use JDownloader since I found DZA, cause is much faster loading and respects my HiDPI screen size without needing to configure nothing.

**Comment by eadmaster** [comment]
i've tried again with the latest linux package on my Ubuntu 22.04 install and i am still getting this error, seems a dependency issue:

````
qt.core.library: "/home/andy/opt/ArrowDL/platforms/libqxcb.so" cannot load: Cannot load library /home/andy/opt/ArrowDL/platforms/libqxcb.so: (/lib/x86_64-linux-gnu/libQt6OpenGL.so.6: undefined symbol: _ZNK14QWindowPrivate12shareContextEv, version Qt_6_PRIVATE_API)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/home/andy/opt/ArrowDL/platforms/libqxcb.so" : "Cannot load library /home/andy/opt/ArrowDL/platforms/libqxcb.so: (/lib/x86_64-linux-gnu/libQt6OpenGL.so.6: undefined symbol: _ZNK14QWindowPrivate12shareContextEv, version Qt_6_PRIVATE_API)"
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

````
